#!/bin/bash 

g++ -std=c++14 \
        -I/home/vittorioromeo/OHWorkspace/vrm_pp/include \
        -I/home/vittorioromeo/OHWorkspace/vrm_core/include \
        -pedantic \
        -W \
        -Wall \
        -Wextra \
        -Wno-unused-local-typedefs \
        -Wwrite-strings \
        -Wundef \
        -Wno-missing-field-initializers \
        -Wpointer-arith \
        -Wcast-align \
        -Wno-unreachable-code \
        -Wnon-virtual-dtor \
        -Woverloaded-virtual \
        -Wsuggest-final-types \
        -Wsuggest-final-methods \
        -Wsuggest-override \
        -Wsuggest-attribute=pure \
        -Wsuggest-attribute=const \
        -Wsuggest-attribute=noreturn \
        -Wsuggest-attribute=format \
        -Wsequence-point \
        -lpthread \
        -lboost_system \
        -lboost_thread \
        -lmarkdown \
        $1 -o /tmp/x.x && /tmp/x.x "${@:2}"