#!/bin/bash

OUT="/tmp/x.x"
INCLUDES="-I/home/vittorioromeo/OHWorkspace/vrm_pp/include"
FLAGS="-std=c++1z -W -Wall -Wextra -Wpedantic -fdiagnostics-color=always $INCLUDES -o $OUT"

GCC="g++"
CLANG="clang++"

$GCC $1 $FLAGS && $OUT