#!/bin/bash

time g++7 -std=c++1z \
    -W -Wall -Wextra -Wpedantic \
    -fdiagnostics-color=always \
    -I"C:\MinGW\include" \
    -I"/home/vittorioromeo/OHWorkspace/vrm_core/include" \
    $1 -o /tmp/x.x # |& ./vv_camomilla.sh

if [ $? == 0 ]; then
    echo "Compiled." && /tmp/x.x "${@:2}"
else
    echo "Failed."
fi
