#!/bin/bash

time g++ -std=c++1z \
    -W -Wall -Wextra -Wpedantic \
    -lpthread \
    -fdiagnostics-color=always \
    $1 -o /tmp/x.x |& ./vv_camomilla.sh

if [ $? == 0 ]; then
    echo "Compiled." && /tmp/x.x "${@:2}" 
else
    echo "Failed."
fi
